### ISSUE TITLE
where is Dynamic and representation  

### ISSUE THREAD

**Issue by Nightbringers** [sr5434/AlphaZero#1]
It looks like still a alphazero,  can you Implementing  muzero in go game?

**Comment by sr5434** [comment]
Just edit the config environment to say "go_9x9"

**Comment by Nightbringers** [comment]
muzero have Dynamic and representation and prediction,  but you code do not have.

**Comment by sr5434** [comment]
Isn’t that implemented in the MuZero gumbel policy from MCTX

**Comment by sr5434** [comment]
Also I can't figure out prediction, but feel free to implement it yourself

**Comment by Nightbringers** [comment]
The representation F output is not policy and value.  It's an  s,  which is the input of Dynamic F or prediction F.  
it's like this:  input ->  representation F ->  s,   s-> prediction F ->  p,v     s -> Dynamic F -> next s   next s ->  prediction F ->  p,v 
you implemented doesn't look like  muzero.
you may need to read muzero paper more carefully.

**Comment by sr5434** [comment]
I decided to just do AlphaZero, as I couldn't understand MuZero very well. However, I used Muax to build a trading algorithm using the true MuZero algorithm, which I just pushed.
